In [ ]:
# Create baseline models: feature engineering (domain knowledge feature) ---> split dataset ---> encoding ---> modeling ---> evaluate models 
# Imports
import os
import sys
import numpy as np
import pandas as pd
from huggingface_hub import login
# Add the utils folder to Python path
notebook_dir = os.path.dirname(os.path.abspath("__file__"))
pricer_path = os.path.join(notebook_dir, "../utils")
sys.path.insert(0, pricer_path)
# Class Item to validate the returned data and has lots of helper functions
from pricer.items import Item
from pricer.evaluator import evaluate
# Machine learning models
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

In [2]:
# Login to Hugging Face
hf_token = os.environ['HF_TOKEN']
login(hf_token, add_to_git_credential=True)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

In [3]:
# Download the batches dataset from Hugging Face 
username = "omarshaarawy11"
dataset = f"{username}/best_deal_03_batches"
train, val, test = Item.from_hub(dataset)
items = train + val + test
print(f"Loaded {len(items):,} items")

Loaded 21,091 items

In [4]:
# Invistigate the dataset
columns = ['title', 
'category', 
'price',
'full',
'weight',
'summary',
'prompt',
'id'
]
for i in columns:
    # Combine item with its attrs
    attr = getattr(items[0], i)
    print(attr)

Lurrose 100Pcs Full Cover Fake Toenails Artificial Transparent Nail Tips Nail Art for DIY
all beauty
6.99
None
0.0
Title: Lurrose 100pcs Full Cover Fake Toenails
Category: Nail Art & Accessories
Brand: Lurrose
Description: High-quality, durable artificial toenails perfect for DIY nail art and manicures.
Details: Features 100 lightweight, eco-friendly ABS nails that are easy to trim, shape, and fit comfortably to natural toenails, suitable for various styles and perfect as a gift.
None
None

In [5]:
# Input features for the ML models
features = list(Item.model_fields.keys())
features.remove('price')
print(features)

['title', 'category', 'full', 'weight', 'summary', 'prompt', 'completion', 'id']

In [6]:
# Feature engineering
# Domain knowledge feature
# We need weight, lenght of the whole summary of the product and the column of weight_unknown in case we don't known about weight
def get_features(item):
    # As long as we work with pydantics we can access any attribute of the object using .
    return {
        "weight": item.weight,
        "weight_unknown": 1 if item.weight==0 else 0,
        "text_length": len(item.summary)
    }

In [7]:
# Split dataset
train = train
test = test

In [8]:
# Convert to dataframe
def list_to_dataframe(items):
    features = [get_features(item) for item in items]
    # Input features
    df = pd.DataFrame(features)
    # Output feature
    df['price'] = [item.price for item in items]
    return df

train_df = list_to_dataframe(train)
test_df = list_to_dataframe(test)

In [9]:
train_df

        weight  weight_unknown  text_length  price
0      0.00000               1          377   6.99
1      0.00000               1          359   5.99
2      0.00000               1          416  29.80
3      0.00000               1          337  24.00
4      0.00000               1          379  22.49
...        ...             ...          ...    ...
16795  0.35000               0          349  17.49
16796  1.01000               0          387  25.97
16797  0.36875               0          421  25.99
16798  3.61000               0          366  49.87
16799  2.14000               0          387  27.88

[16800 rows x 4 columns]

In [10]:
test_df

        weight  weight_unknown  text_length  price
0      0.65625               0          353   8.99
1     13.80000               0          347  49.99
2      0.56875               0          353   9.99
3      1.50000               0          319  21.99
4      2.79000               0          365  32.99
...        ...             ...          ...    ...
2186   0.00000               1          317  50.00
2187   0.00000               1          330  50.00
2188   0.00000               1          316  12.99
2189   0.03300               0          311  25.00
2190   0.00000               1          359  50.00

[2191 rows x 4 columns]

In [11]:
# Modeling
# Traditional linear regression
# The results of train and test is not good enough so our feature selection is not good enough
np.random.seed(40)
feature_columns = ['weight', 'weight_unknown', 'text_length']
X_train = train_df[feature_columns]
y_train = train_df['price']
X_test = test_df[feature_columns]
y_test = test_df['price']

# Train 
model = LinearRegression()
model.fit(X_train, y_train)
for feature, coef in zip(feature_columns, model.coef_):
    print(f"{feature}: {coef: 0.2f}")
print(f"Intercept: {model.intercept_: 0.2f}")

# Predict 
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluate 
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MSE: {train_mse: 0.2f}")
print(f"Train R2 Score: {train_r2: 0.2f}%")
print(f"Test MSE: {test_mse: 0.2f}")
print(f"Test R2 Score: {test_r2: 0.2f}%")

weight:  4.25
weight_unknown:  0.82
text_length:  0.09
Intercept:  12.38
Train MSE:  8252.34
Train R2 Score:  0.24%
Test MSE:  3520.26
Test R2 Score:  0.43%

In [12]:
# Test dataset
def linear_regression_pricer(item):
    features = get_features(item)
    features_df = pd.DataFrame([features])
    # The new coming data points we work with .predict
    # [0] the prediction of the model
    return model.predict(features_df)[0]

In [13]:
# Test single datapoint
linear_regression_pricer(items[0])

45.81016596666426

In [14]:
# Evaluation
evaluate(linear_regression_pricer, test)

  0%|          | 0/2000 [00:00<?, ?it/s]

$37 $51 $35 $24 $23 $26 $27 $22 $30 $33 $16 $23 $34 $45 $36 $38 $31 $19 $130 $4 $34 $31 $17 $29 $38 $30 $31 $50 $29 $15 $25 $34 $28 $561 $32 $27 $23 $27 $88 $26 $31 $41 $35 $12 $14 $34 $32 $30 $37 $14 $34 $36 $33 $30 $29 $31 $7 $11 $35 $35 $50 $31 $45 $33 $36 $26 $41 $17 $34 $22 $32 $28 $30 $25 $13 $19 $18 $9 $7 $167 $3 $26 $42 $31 $21 $38 $31 $38 $24 $33 $32 $31 $39 $39 $12 $35 $28 $15 $38 $25 $32 $22 $36 $31 $40 $36 $34 $7 $4 $21 $19 $13 $17 $100 $25 $43 $25 $46 $34 $7 $10 $9 $30 $24 $13 $0 $5 $31 $33 $27 $31 $34 $99 $212 $28 $29 $25 $35 $43 $32 $31 $16 $35 $31 $35 $34 $31 $4 $27 $34 $2 $12 $27 $13 $51 $1 $32 $29 $45 $30 $25 $16 $36 $33 $20 $224 $30 $39 $39 $28 $34 $30 $92 $114 $27 $32 $33 $22 $25 $19 $37 $23 $35 $22 $213 $14 $3 $29 $25 $30 $13 $24 $25 $42 $37 $28 $41 $34 $32 $39 $33 $17 $5 $25 $33 $28 $34 $33 $13 $25 $29 $48 $6 $27 $21 $5 $27 $21 $27 $29 $34 $35 $35 $34 $26 $40 $35 $8 $18 $37 $28 $37 $37 $38 $32 $43 $31 $32 $28 $28 $25 $34 $33 $39 $33 $29 $33 $41 $32 $90 $1 $29 $26 $27 $52 $623 $24 $36 $7 $4 $28 $32 $40 $18 $36 $14 $23 $37 $69 $27 $41 $56 $31 $25 $31 $22 $14 $27 $7 $26 $46 $43 $16 $31 $54 $34 $49 $37 $21 $14 $57 $29 $46 $26 $14 $29 $34 $60 $41 $42 $22 $41 $48 $150 $16 $36 $27 $35 $25 $12 $39 $151 $23 $12 $25 $33 $39 $16 $26 $23 $33 $34 $30 $31 $33 $34 $29 $39 $25 $24 $0 $13 $151 $22 $39 $21 $19 $46 $23 $39 $46 $29 $30 $45 $13 $34 $27 $7 $25 $40 $39 $32 $30 $615 $15 $21 $29 $371 $4 $15 $34 $22 $31 $32 $14 $26 $5 $20 $39 $28 $27 $9 $31 $35 $31 $33 $17 $33 $15 $10 $33 $17 $31 $32 $13 $19 $33 $22 $2 $93 $38 $30 $22 $33 $31 $28 $30 $10 $19 $230 $12 $32 $68 $29 $3 $26 $33 $24 $30 $23 $35 $18 $1 $1 $8 $25 $37 $34 $27 $35 $2 $21 $35 $37 $17 $40 $29 $28 $37 $22 $25 $42 $15 $39 $31 $24 $33 $29 $27 $302 $30 $17 $25 $35 $21 $29 $33 $6 $37 $28 $24 $27 $8 $11 $30 $37 $3 $16 $12 $33 $33 $20 $26 $1 $23 $9 $25 $19 $14 $39 $79 $27 $15 $40 $19 $25 $33 $41 $35 $24 $26 $34 $134 $10 $26 $39 $704 $24 $36 $28 $32 $1 $35 $6 $12 $27 $26 $34 $19 $16 $105 $38 $19 $78 $5 $19 $30 $25 $19 $29 $14 $22 $31 $6 $98 $59 $29 $14 $42 $8 $24 $30 $41 $47 $40 $102 $23 $3 $27 $26 $25 $14 $38 $58 $14 $27 $15 $7 $1 $24 $42 $36 $22 $32 $20 $100 $2 $24 $27 $28 $100 $2 $18 $0 $20 $38 $25 $113 $37 $39 $31 $20 $30 $29 $2 $18 $28 $28 $15 $34 $0 $4 $33 $21 $39 $22 $2 $332 $32 $89 $30 $9 $19 $31 $29 $5 $31 $24 $18 $33 $20 $36 $92 $22 $34 $16 $249 $39 $21 $22 $35 $36 $31 $8 $36 $34 $38 $18 $35 $41 $35 $34 $30 $37 $20 $32 $28 $32 $14 $31 $29 $154 $30 $24 $9 $33 $34 $16 $35 $82 $5 $38 $28 $32 $31 $23 $23 $30 $34 $9 $35 $13 $243 $30 $8 $27 $40 $20 $166 $6 $24 $34 $37 $26 $30 $31 $32 $60 $29 $32 $23 $27 $32 $70 $33 $17 $18 $35 $27 $20 $6 $32 $36 $1 $17 $40 $26 $30 $46 $50 $38 $14 $12 $30 $31 $26 $44 $15 $8 $129 $15 $12 $30 $14 $34 $12 $35 $2 $23 $34 $32 $14 $27 $18 $29 $35 $49 $69 $26 $14 $36 $10 $166 $26 $27 $29 $29 $26 $18 $2 $10 $28 $26 $33 $44 $36 $11 $4 $37 $34 $28 $1 $38 $15 $28 $31 $25 $41 $15 $20 $1 $45 $19 $75 $35 $34 $11 $12 $38 $28 $29 $37 $38 $80 $10 $34 $30 $24 $19 $20 $33 $5 $49 $35 $37 $41 $30 $13 $5 $33 $1 $13 $22 $13 $58 $20 $18 $24 $24 $18 $28 $28 $41 $26 $33 $26 $1 $30 $36 $12 $11 $437 $41 $22 $31 $35 $20 $5 $3 $34 $26 $15 $16 $22 $36 $15 $1 $1 $22 $30 $14 $24 $9 $31 $20 $6 $26 $1 $14 $27 $26 $16 $21 $13 $20 $27 $31 $358 $37 $27 $33 $38 $41 $14 $1 $21 $29 $32 $154 $39 $37 $118 $42 $112 $32 $41 $26 $33 $30 $23 $20 $41 $40 $36 $19 $9 $17 $14 $40 $40 $37 $9 $124 $13 $81 $5 $25 $48 $59 $24 $27 $13 $29 $38 $11 $15 $5 $32 $35 $164 $21 $38 $103 $32 $30 $32 $58 $25 $44 $24 $32 $31 $21 $31 $26 $26 $38 $31 $27 $37 $39 $9 $19 $30 $28 $30 $13 $26 $64 $41 $16 $65 $20 $21 $304 $29 $29 $41 $14 $35 $5 $21 $40 $11 $37 $35 $34 $22 $2 $38 $25 $35 $35 $15 $72 $0 $27 $31 $34 $34 $11 $129 $4 $41 $21 $30 $20 $31 $20 $46 $42 $50 $56 $22 $26 $33 $20 $86 $25 $38 $22 $26 $27 $25 $31 $19 $36 $14 $21 $32 $34 $10 $16 $41 $34 $32 $10 $34 $32 $10 $37 $31 $191 $31 $30 $30 $30 $9 $18 $34 $25 $33 $26 $32 $88 $46 $21 $39 $24 $27 $4 $33 $11 $34 $38 $25 $9 $36 $26 $30 $28 $27 $32 $25 $29 $22 $21 $366 $56 $14 $28 $30 $36 $36 $31 $23 $38 $11 $27 $42 $25 $117 $28 $32 $40 $17 $20 $26 $27 $35 $52 $55 $33 $6 $26 $242 $43 $38 $32 $93 $22 $35 $9 $34 $33 $44 $15 $26 $36 $3 $41 $29 $19 $33 $35 $29 $39 $651 $41 $92 $31 $25 $37 $17 $28 $175 $115 $21 $34 $28 $33 $18 $30 $34 $22 $21 $21 $19 $33 $36 $35 $30 $29 $31 $101 $26 $25 $9 $7 $24 $35 $34 $16 $31 $30 $33 $21 $30 $34 $81 $13 $99 $33 $35 $36 $22 $24 $39 $26 $33 $33 $32 $9 $34 $13 $31 $13 $3 $29 $29 $31 $32 $37 $35 $24 $0 $29 $18 $29 $26 $30 $22 $8 $19 $8 $27 $22 $107 $44 $109 $24 $36 $34 $10 $24 $32 $21 $12 $21 $37 $36 $20 $41 $58 $31 $33 $30 $21 $27 $50 $1 $31 $3 $27 $26 $33 $31 $29 $19 $29 $32 $23 $26 $15 $20 $29 $21 $29 $39 $41 $3 $58 $41 $29 $19 $8 $78 $20 $33 $39 $41 $23 $37 $5 $124 $23 $32 $22 $29 $1 $19 $25 $38 $39 $23 $38 $39 $5 $1 $10 $45 $28 $20 $57 $31 $24 $56 $32 $28 $28 $76 $23 $36 $30 $30 $34 $28 $98 $33 $36 $34 $28 $29 $31 $32 $12 $38 $36 $22 $29 $32 $42 $13 $32 $34 $34 $37 $67 $35 $2 $20 $39 $39 $32 $11 $36 $35 $88 $16 $24 $28 $18 $25 $29 $8 $18 $20 $0 $14 $28 $38 $48 $32 $76 $41 $16 $130 $5 $35 $7 $28 $11 $28 $38 $30 $36 $34 $36 $41 $31 $8 $33 $38 $34 $13 $3 $424 $29 $16 $32 $11 $30 $37 $40 $31 $24 $31 $3 $39 $30 $29 $7 $29 $33 $35 $37 $19 $46 $25 $39 $15 $30 $30 $40 $37 $31 $25 $32 $13 $39 $34 $30 $24 $1 $10 $371 $47 $23 $22 $27 $34 $227 $38 $35 $61 $23 $31 $27 $20 $24 $30 $20 $36 $23 $30 $28 $10 $12 $29 $14 $55 $15 $35 $26 $35 $30 $14 $20 $31 $16 $101 $23 $34 $38 $29 $22 $36 $38 $25 $38 $35 $141 $36 $31 $42 $36 $35 $19 $33 $32 $22 $19 $27 $5 $21 $38 $45 $33 $31 $35 $10 $11 $41 $14 $39 $34 $37 $34 $37 $32 $35 $35 $26 $34 $19 $2 $95 $107 $25 $26 $24 $15 $34 $32 $22 $31 $32 $18 $30 $91 $37 $32 $30 $26 $214 $23 $36 $24 $37 $29 $16 $25 $34 $33 $13 $30 $53 $15 $38 $156 $17 $139 $33 $36 $56 $36 $38 $37 $14 $30 $33 $8 $33 $13 $34 $32 $33 $33 $31 $32 $36 $14 $61 $1 $27 $14 $28 $34 $37 $22 $26 $23 $32 $2 $29 $57 $33 $33 $32 $37 $27 $29 $22 $9 $24 $0 $34 $34 $13 $22 $32 $27 $2 $70 $23 $33 $188 $155 $10 $46 $42 $1 $25 $41 $33 $10 $63 $32 $82 $24 $18 $38 $21 $26 $7 $31 $31 $34 $211 $38 $21 $25 $24 $23 $18 $34 $34 $16 $15 $28 $36 $31 $24 $28 $27 $1 $19 $56 $38 $69 $5 $52 $31 $17 $39 $10 $36 $15 $39 $23 $31 $8 $32 $17 $29 $25 $20 $25 $36 $34 $25 $24 $27 $39 $24 $24 $4 $6 $399 $35 $3 $26 $36 $29 $36 $7 $29 $33 $24 $16 $4 $173 $22 $42 $31 $24 $6 $29 $7 $33 $33 $28 $7 $34 $24 $39 $37 $303 $36 $239 $39 $134 $35 $99 $1 $37 $34 $23 $14 $99 $41 $36 $56 $27 $11 $8 $13 $32 $32 $30 $20 $28 $31 $24 $21 $32 $7 $16 $10 $23 $46 $25 $26 $32 $38 $149 $26 $94 $26 $35 $28 $195 $31 $36 $16 $28 $16 $29 $36 $35 $15 $30 $12 $35 $33 $27 $25 $20 $25 $35 $7 $91 $3 $9 $30 $39 $27 $32 $37 $15 $31 $22 $14 $19 $41 $34 $37 $24 $9 $39 $2 $35 $22 $32 $18 $35 $28 $41 $29 $23 $0 $34 $35 $25 $33 $0 $113 $14 $254 $23 $23 $31 $39 $105 $21 $10 $6 $27 $100 $18 $40 $29 $19 $20 $33 $32 $47 $33 $33 $7 $27 $17 $25 $37 $31 $22 $28 $31 $31 $32 $30 $24 $339 $15 $46 $21 $24 $31 $10 $26 $33 $16 $9 $10 $18 $48 $39 $31 $12 $26 $5 $0 $24 $41 $21 $15 $31 $18 $34 $102 $25 $3 $1 $50 $28 $32 $19 $37 $37 $34 $24 $251 $43 $26 $18 $18 $138 $30 $41 $22 $98 $27 $36 $31 $31 $27 $2 $1 $23 $31 $39 $64 $36 $22 $35 $29 $38 $33 $216 $13 $30 $32 $33 $19 $28 $35 $62 $18 $14 $19 $13 $38 $20 $31 $6 $22 $6 $25 $27 $33 $14 $36 $38 $157 $34 $26 $28 $22 $122 $33 $30 $8 $23 $36 $21 $34 $45 $27 $28 $326 $28 $9 $11 $10 $24 $21 $25 $11 $6 $11 $13 $15 $4 $4 $16 $20 $16 $59 $17 $7 $60 $12 $11 $18 $33 $8 $14 $6 $14 $14 $10 $38 $21 $4 $10 $7 $7 $23 $18 $52 $17 $13 $85 $9 $10 $160 $6 $157 $16 $58 $10 $3 $14 $16 $9 $20 $16 $156 $9 $14 $22 $8 $20 $18 $8 $66 $14 $8 $12 $8 $28 $58 $13 $459 $57 $3 $28 $19 $21 $1 $7 $9 $7 $21 $12 $6 $1 $15 $14 $11 $62 $15 $18 $16 $16 $21 $64 $17 $12 $11 $19 $7 $15 $7 $12 $16 $3 $25 $13 $15 $2 $26 $9 $17 $15 $110 $31 $16 $6 $10 $17 $16 $25 $18 $14 $9 $8 $13 $13 $84 $12 $9 $1 $16 $18 $60 $14 $22 $17 $159

In [15]:
# Feature engineering
# Domain knowledge feature
# The performance of traditional linear regression is not good enough 
# So we add new useful feature
prices_train = np.array([float(item.price) for item in train])
prices_test = np.array([float(item.price) for item in test])
# Apply NLP 
# Add corpus
# Then we come up with the most k-words in corpus and treeat them as seperated features
documents_train = [item.summary for item in train]
documents_test = [item.summary for item in test]

In [16]:
# Encoding
# Apply count vectorizer to form new X_train and X_test
np.random.seed(40)
# Ignore stop English words, We need the important ones
vectorizer = CountVectorizer(max_features=450, stop_words='english')
X_train = vectorizer.fit_transform(documents_train)
X_test = vectorizer.transform(documents_test)

In [17]:
selected_words = vectorizer.get_feature_names_out()
print(f"Number of selected words 'famous' in both train and test: {len(selected_words)}")
print("Selected words in train and test:", selected_words)

Number of selected words 'famous' in both train and test: 450
Selected words in train and test: ['10' '100' '11' '12' '13' '14' '15' '16' '20' '24' '25' '30' '360' '4k'
 '50' 'ac' 'access' 'accessories' 'adapter' 'adhesive' 'adjustable' 'air'
 'airpods' 'aluminum' 'anti' 'apple' 'appliance' 'appliances'
 'approximately' 'art' 'assembly' 'audio' 'auto' 'available' 'backdrop'
 'backed' 'bag' 'bags' 'basket' 'bathroom' 'batteries' 'battery' 'bedding'
 'belt' 'black' 'blue' 'bluetooth' 'board' 'body' 'bpa' 'brand' 'brands'
 'breathable' 'built' 'burner' 'cable' 'cables' 'camera' 'cameras'
 'canvas' 'capacity' 'car' 'carbon' 'card' 'care' 'case' 'category'
 'ceramic' 'certified' 'charger' 'charging' 'christmas' 'clean' 'cleaning'
 'clear' 'closure' 'coffee' 'color' 'colorful' 'colors' 'comes' 'comfort'
 'comfortable' 'compact' 'compatibility' 'compatible' 'components'
 'comprehensive' 'connectivity' 'connector' 'connectors' 'construction'
 'control' 'controls' 'convenient' 'cooling' 'copper' 'cord' 'cotton'
 'cover' 'covers' 'crafted' 'cup' 'curtain' 'customizable' 'data' 'day'
 'decor' 'decorations' 'decorative' 'description' 'design' 'designed'
 'details' 'device' 'devices' 'digital' 'dining' 'dishwasher'
 'dishwashers' 'display' 'door' 'double' 'drain' 'drive' 'dryer' 'dryers'
 'dual' 'durability' 'durable' 'dust' 'duty' 'ear' 'easy' 'eco'
 'effective' 'efficient' 'egg' 'electric' 'electronics' 'elegant'
 'element' 'energy' 'enhance' 'enhanced' 'ensure' 'ensuring' 'equipment'
 'ergonomic' 'ethernet' 'fabric' 'fan' 'fast' 'features' 'featuring'
 'festive' 'filter' 'filters' 'filtration' 'finish' 'fit' 'fits'
 'flexible' 'floral' 'foam' 'foldable' 'food' 'foot' 'frame' 'free'
 'freezer' 'fresh' 'friendly' 'frigidaire' 'ft' 'function' 'furniture'
 'galaxy' 'gaming' 'gas' 'gasket' 'ge' 'genuine' 'glass' 'gold' 'grade'
 'green' 'hair' 'hand' 'handle' 'handles' 'hanging' 'hard' 'hd' 'hdmi'
 'heat' 'heating' 'heavy' 'high' 'holder' 'holiday' 'home' 'hood' 'hot'
 'hp' 'humidifier' 'ice' 'ideal' 'improve' 'inch' 'inches' 'include'
 'included' 'includes' 'including' 'indoor' 'inlet' 'install'
 'installation' 'ipad' 'kenmore' 'keyboard' 'kids' 'kit' 'kitchen' 'knob'
 'laptop' 'laptops' 'large' 'lasting' 'layer' 'lcd' 'leather' 'led'
 'length' 'lens' 'lg' 'lid' 'life' 'lifespan' 'lifetime' 'light'
 'lighting' 'lightweight' 'like' 'lint' 'living' 'lock' 'long' 'low'
 'macbook' 'machine' 'machines' 'magnetic' 'major' 'maker' 'material'
 'materials' 'maytag' 'measures' 'measuring' 'memory' 'mesh' 'metal'
 'microfiber' 'mini' 'models' 'modern' 'months' 'motor' 'mount' 'mounting'
 'multi' 'multiple' 'natural' 'noise' 'non' 'nsf' 'nylon' 'occasions'
 'oem' 'offering' 'offers' 'office' 'operation' 'optimal' 'options'
 'organization' 'outdoor' 'output' 'oven' 'pack' 'panel' 'paper' 'parts'
 'party' 'pattern' 'perfect' 'performance' 'personal' 'photography'
 'piece' 'pillow' 'plastic' 'plated' 'plug' 'pocket' 'pockets' 'polyester'
 'portable' 'ports' 'power' 'precise' 'premium' 'prevent' 'pro'
 'professional' 'proof' 'proper' 'protect' 'protection' 'protective'
 'protector' 'providing' 'pump' 'pure' 'quality' 'quick' 'rack' 'ram'
 'range' 'ranges' 'red' 'reduce' 'refrigerator' 'refrigerators' 'reliable'
 'remote' 'removable' 'replacement' 'resistance' 'resistant' 'resolution'
 'reusable' 'room' 'rubber' 'safe' 'safety' 'samsung' 'screen' 'seal'
 'seamless' 'secure' 'security' 'select' 'self' 'sensor' 'series' 'set'
 'shaped' 'sheet' 'shelf' 'shell' 'shockproof' 'silicone' 'size' 'sizes'
 'skin' 'sleek' 'sleep' 'slim' 'slip' 'small' 'smart' 'smooth' 'soft'
 'sound' 'space' 'speaker' 'specific' 'specifically' 'speed' 'stainless'
 'stand' 'standard' 'standards' 'steel' 'storage' 'stove' 'strap' 'sturdy'
 'style' 'stylish' 'suitable' 'supplies' 'supply' 'support' 'supporting'
 'supports' 'surface' 'switch' 'systems' 'table' 'tablets' 'technology'
 'temperature' 'themed' 'thermal' 'thermostat' 'timer' 'title' 'tools'
 'touch' 'transfer' 'travel' 'tv' 'ultra' 'universal' 'usa' 'usb' 'use'
 'uv' 'valve' 'various' 'vent' 'versatile' 'vibrant' 'video' 'viewing'
 'vintage' 'vinyl' 'voltage' 'wall' 'warranty' 'wash' 'washable' 'washer'
 'washers' 'washing' 'water' 'waterproof' 'whirlpool' 'white' 'wide'
 'window' 'wire' 'wireless' 'wood' 'wooden' 'year']

In [18]:
X_train

<16800x450 sparse matrix of type '<class 'numpy.int64'>'
	with 367666 stored elements in Compressed Sparse Row format>

In [19]:
X_test

<2191x450 sparse matrix of type '<class 'numpy.int64'>'
	with 42425 stored elements in Compressed Sparse Row format>

In [20]:
# Modeling
# Traditional linear regression with NLP features
np.random.seed(40)
feature_columns = selected_words
y_train = prices_train
y_test = prices_test

# Train 
model = LinearRegression()
model.fit(X_train, y_train)
for feature, coef in zip(feature_columns, model.coef_):
    print(f"{feature}: {coef: 0.2f}")
print(f"Intercept: {model.intercept_: 0.2f}")

# Predict 
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluate 
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MSE: {train_mse: 0.2f}")
print(f"Train R2 Score: {train_r2: 0.2f}%")
print(f"Test MSE: {test_mse: 0.2f}")
print(f"Test R2 Score: {test_r2: 0.2f}%")

10: -1.17
100:  5.42
11:  3.67
12:  1.45
13:  5.55
14:  5.22
15:  16.60
16:  8.29
20:  14.94
24:  33.72
25:  5.14
30:  25.61
360: -8.09
4k:  17.39
50:  10.54
ac: -0.34
access: -3.80
accessories: -8.98
adapter: -6.18
adhesive: -12.70
adjustable:  4.30
air:  1.37
airpods:  0.03
aluminum: -10.82
anti: -1.95
apple:  9.94
appliance:  8.64
appliances:  13.38
approximately: -7.28
art: -11.25
assembly:  16.88
audio:  1.92
auto:  6.13
available: -9.65
backdrop: -19.72
backed: -5.87
bag: -11.76
bags: -10.00
basket: -6.99
bathroom: -4.16
batteries: -3.39
battery: -15.57
bedding:  27.97
belt: -4.56
black: -2.96
blue: -0.49
bluetooth: -6.59
board:  19.00
body: -0.97
bpa: -5.75
brand: -6.54
brands: -12.13
breathable: -0.25
built:  41.30
burner: -4.05
cable: -7.88
cables:  2.37
camera:  2.72
cameras:  11.57
canvas:  6.36
capacity:  15.64
car:  0.83
carbon:  6.26
card: -3.00
care: -6.66
case: -4.20
category: -25.43
ceramic: -4.66
certified:  5.30
charger: -4.26
charging: -5.13
christmas: -2.95
clean:  2.15
cleaning: -1.89
clear: -4.83
closure: -4.00
coffee: -2.46
color: -2.20
colorful: -4.70
colors:  1.34
comes:  0.22
comfort:  5.55
comfortable: -0.07
compact:  6.74
compatibility: -10.47
compatible: -10.66
components: -3.23
comprehensive:  11.21
connectivity:  27.85
connector: -15.98
connectors: -11.98
construction: -7.17
control:  12.37
controls:  45.99
convenient:  4.11
cooling:  7.66
copper: -1.60
cord: -8.82
cotton: -3.38
cover: -2.33
covers:  1.56
crafted: -0.13
cup: -0.24
curtain:  2.46
customizable:  12.68
data: -3.35
day: -4.29
decor: -4.73
decorations: -5.54
decorative: -6.61
description: -0.00
design: -4.11
designed: -5.46
details: -14.34
device: -12.68
devices: -16.12
digital:  3.38
dining: -3.26
dishwasher:  6.97
dishwashers: -6.22
display:  26.12
door:  9.01
double: -1.54
drain: -0.52
drive: -0.88
dryer:  0.47
dryers: -7.18
dual:  9.77
durability:  1.99
durable: -7.25
dust: -0.81
duty:  25.01
ear: -12.95
easy: -5.48
eco:  3.16
effective: -8.19
efficient:  15.88
egg: -16.52
electric:  13.11
electronics:  1.02
elegant: -2.63
element: -9.03
energy:  22.73
enhance: -8.28
enhanced: -6.43
ensure: -1.98
ensuring: -8.07
equipment:  39.15
ergonomic: -11.94
ethernet: -1.76
fabric: -4.18
fan: -10.72
fast:  7.27
features:  7.69
featuring:  10.96
festive: -0.07
filter: -5.70
filters:  3.60
filtration: -2.65
finish: -2.03
fit: -1.74
fits: -6.15
flexible: -2.61
floral: -3.59
foam:  21.45
foldable: -1.43
food: -6.23
foot: -7.32
frame:  4.42
free: -0.16
freezer:  16.79
fresh: -3.96
friendly: -4.81
frigidaire:  6.00
ft:  45.53
function: -10.78
furniture:  58.48
galaxy: -2.44
gaming:  32.06
gas:  11.26
gasket: -1.60
ge: -0.31
genuine: -3.06
glass:  6.50
gold: -4.87
grade:  5.38
green:  0.14
hair: -4.29
hand: -2.56
handle: -12.04
handles: -4.47
hanging: -10.71
hard:  6.01
hd:  6.41
hdmi: -11.58
heat: -0.93
heating:  5.16
heavy: -23.70
high:  8.26
holder: -10.78
holiday: -6.17
home: -1.12
hood:  40.82
hot: -6.66
hp:  14.94
humidifier: -0.55
ice:  8.96
ideal: -3.57
improve:  0.23
inch:  5.79
inches: -1.65
include:  15.80
included: -5.68
includes:  3.70
including:  5.23
indoor: -4.85
inlet:  0.37
install: -0.02
installation: -0.80
ipad: -3.76
kenmore: -6.22
keyboard:  3.64
kids: -2.28
kit: -2.32
kitchen: -0.92
knob: -16.41
laptop:  30.37
laptops: -20.67
large:  4.53
lasting: -13.05
layer: -0.20
lcd: -14.57
leather:  1.72
led: -8.14
length: -13.42
lens:  12.26
lg:  1.85
lid: -5.43
life:  9.30
lifespan: -11.12
lifetime: -20.80
light: -8.22
lighting:  24.00
lightweight:  0.16
like: -5.94
lint:  2.28
living:  5.54
lock:  10.58
long: -3.41
low:  14.84
macbook: -15.04
machine: -0.30
machines: -2.55
magnetic: -2.92
major:  9.06
maker:  6.39
material: -3.05
materials: -1.41
maytag:  0.15
measures:  2.17
measuring: -8.73
memory: -10.30
mesh: -8.26
metal: -6.73
microfiber: -14.72
mini: -7.75
models: -4.76
modern:  18.07
months: -8.26
motor:  7.15
mount:  4.61
mounting: -14.92
multi: -0.67
multiple:  5.86
natural: -6.55
noise: -12.35
non: -11.56
nsf: -11.66
nylon: -5.12
occasions: -5.22
oem:  6.37
offering: -0.83
offers: -4.26
office:  2.44
operation:  1.00
optimal: -6.21
options:  5.95
organization: -11.36
outdoor:  9.24
output:  0.37
oven:  9.72
pack: -8.26
panel:  7.16
paper: -5.68
parts: -4.03
party: -1.49
pattern: -4.71
perfect: -14.00
performance:  19.32
personal: -3.05
photography:  10.65
piece:  1.43
pillow: -5.15
plastic: -8.35
plated: -10.81
plug: -13.23
pocket:  1.23
pockets: -12.52
polyester: -4.84
portable: -1.28
ports:  12.65
power:  1.99
precise: -0.91
premium:  9.53
prevent: -9.40
pro:  7.12
professional:  33.79
proof: -10.92
proper: -6.43
protect: -9.59
protection: -12.51
protective: -8.71
protector: -9.11
providing: -2.11
pump:  5.95
pure:  2.65
quality: -10.03
quick: -7.06
rack: -2.25
ram:  126.47
range:  8.37
ranges: -8.43
red: -3.92
reduce: -1.09
refrigerator:  3.77
refrigerators:  1.53
reliable: -8.83
remote: -7.23
removable:  7.30
replacement: -6.22
resistance: -5.96
resistant: -8.64
resolution:  21.71
reusable: -2.42
room:  3.82
rubber: -10.15
safe: -1.69
safety: -0.08
samsung:  2.13
screen: -5.67
seal: -3.58
seamless:  4.95
secure: -7.00
security:  9.11
select: -6.93
self:  9.55
sensor: -18.87
series: -3.76
set: -4.42
shaped: -12.39
sheet: -0.10
shelf: -4.87
shell: -6.31
shockproof: -3.35
silicone: -2.52
size: -2.61
sizes: -8.59
skin: -8.65
sleek:  55.04
sleep: -11.39
slim: -2.90
slip: -0.08
small:  8.45
smart:  15.84
smooth: -7.70
soft: -6.11
sound:  13.29
space:  4.06
speaker: -6.07
specific: -2.59
specifically: -10.14
speed: -5.23
stainless:  11.37
stand: -10.96
standard: -4.84
standards: -3.08
steel:  1.57
storage:  10.27
stove: -3.51
strap: -8.47
sturdy:  1.53
style: -1.75
stylish: -1.61
suitable: -7.79
supplies: -8.42
supply: -2.06
support:  3.88
supporting: -3.92
supports: -3.36
surface:  8.74
switch: -10.81
systems:  0.68
table:  0.93
tablets: -8.20
technology:  26.57
temperature:  6.57
themed: -4.06
thermal: -0.62
thermostat: -0.26
timer:  8.18
title: -9.51
tools: -11.19
touch:  17.86
transfer:  3.44
travel: -7.22
tv:  8.95
ultra:  5.13
universal: -12.03
usa: -10.95
usb: -5.99
use: -2.39
uv:  0.71
valve: -4.60
various: -2.63
vent: -7.04
versatile:  10.20
vibrant: -5.52
video:  8.07
viewing:  1.55
vintage:  3.93
vinyl: -8.79
voltage: -16.52
wall:  0.33
warranty: -7.03
wash:  23.58
washable: -5.06
washer:  2.66
washers:  1.41
washing: -3.08
water:  0.33
waterproof: -2.72
whirlpool:  2.15
white: -4.99
wide: -1.87
window: -3.30
wire:  2.32
wireless: -6.09
wood:  11.37
wooden: -4.84
year: -0.69
Intercept:  116.01
Train MSE:  6452.27
Train R2 Score:  0.41%
Test MSE:  4753.48
Test R2 Score:  0.23%

In [21]:
# Test dataset
def linear_regression_pricer_nlp(item):
    X_test = vectorizer.transform([item.summary])
    # In case we got - result then it gonna be zero
    return max(model.predict(X_test)[0], 0)

In [22]:
# Test single datapoint
linear_regression_pricer_nlp(items[0])

0

In [23]:
# Evaluation
evaluate(linear_regression_pricer_nlp, test)

  0%|          | 0/2000 [00:00<?, ?it/s]

$42 $77 $14 $13 $59 $19 $6 $24 $9 $3 $26 $23 $48 $28 $12 $1 $38 $4 $332 $81 $7 $77 $50 $38 $8 $28 $2 $32 $11 $5 $20 $6 $8 $728 $3 $71 $43 $4 $65 $20 $90 $177 $36 $37 $30 $34 $21 $16 $3 $6 $25 $55 $41 $14 $9 $7 $32 $49 $66 $8 $36 $25 $22 $54 $136 $111 $20 $3 $26 $33 $4 $15 $34 $28 $18 $23 $25 $33 $29 $188 $51 $1 $31 $112 $29 $11 $6 $37 $29 $14 $10 $11 $10 $24 $23 $13 $2 $51 $45 $1 $25 $13 $12 $42 $7 $67 $33 $55 $26 $15 $29 $31 $55 $99 $3 $76 $9 $53 $12 $63 $43 $25 $40 $27 $29 $15 $11 $11 $12 $50 $13 $44 $159 $77 $25 $6 $2 $12 $17 $14 $45 $34 $7 $8 $6 $18 $6 $38 $6 $125 $27 $3 $12 $40 $34 $31 $23 $19 $30 $16 $45 $49 $19 $9 $84 $246 $35 $87 $59 $30 $20 $105 $105 $85 $6 $158 $15 $16 $55 $8 $13 $19 $11 $11 $114 $19 $9 $63 $11 $8 $65 $9 $85 $9 $12 $91 $60 $8 $19 $37 $23 $5 $40 $62 $15 $47 $64 $25 $20 $41 $9 $6 $11 $14 $21 $105 $37 $36 $94 $6 $7 $33 $15 $43 $1 $32 $45 $25 $38 $3 $24 $32 $8 $2 $48 $34 $116 $7 $8 $55 $25 $1 $24 $3 $29 $21 $20 $26 $119 $340 $20 $37 $23 $8 $17 $508 $116 $20 $40 $50 $3 $24 $3 $36 $36 $80 $28 $30 $27 $102 $68 $21 $17 $16 $7 $24 $46 $66 $44 $19 $67 $8 $19 $10 $42 $36 $56 $5 $71 $83 $68 $39 $76 $31 $10 $32 $13 $53 $39 $219 $19 $204 $38 $66 $14 $7 $19 $0 $108 $36 $5 $116 $22 $33 $63 $7 $44 $145 $24 $10 $4 $29 $24 $12 $18 $41 $20 $1 $50 $22 $71 $42 $231 $20 $9 $65 $10 $31 $25 $23 $1 $30 $85 $5 $30 $7 $55 $31 $2 $30 $7 $40 $1 $577 $24 $30 $7 $49 $29 $82 $34 $1 $28 $34 $87 $1 $2 $49 $86 $14 $26 $17 $4 $42 $68 $44 $42 $50 $19 $17 $29 $7 $11 $13 $18 $16 $46 $13 $7 $160 $32 $41 $27 $13 $65 $120 $13 $74 $58 $48 $9 $4 $106 $25 $37 $70 $17 $2 $16 $89 $9 $33 $41 $9 $67 $40 $10 $6 $109 $30 $88 $39 $19 $3 $52 $28 $20 $78 $3 $12 $6 $97 $4 $45 $25 $18 $6 $16 $5 $76 $25 $62 $12 $25 $7 $27 $15 $33 $27 $22 $22 $2 $22 $5 $52 $11 $4 $24 $8 $82 $14 $5 $16 $19 $48 $22 $9 $26 $31 $2 $34 $16 $49 $33 $17 $3 $19 $11 $4 $12 $16 $4 $138 $8 $55 $75 $576 $13 $0 $19 $7 $58 $31 $15 $45 $7 $2 $71 $40 $54 $149 $19 $26 $43 $56 $35 $5 $115 $22 $43 $12 $5 $63 $67 $41 $83 $4 $35 $13 $5 $65 $13 $17 $6 $23 $134 $30 $1 $3 $18 $13 $39 $49 $98 $2 $6 $50 $77 $26 $17 $40 $28 $26 $45 $9 $148 $25 $27 $33 $11 $100 $24 $6 $22 $16 $8 $28 $148 $35 $14 $60 $26 $12 $11 $23 $7 $21 $38 $40 $115 $86 $75 $12 $7 $54 $9 $11 $281 $76 $78 $41 $137 $118 $6 $4 $25 $44 $68 $3 $18 $16 $32 $48 $27 $21 $28 $73 $60 $10 $9 $22 $16 $28 $38 $8 $9 $29 $23 $26 $4 $16 $16 $42 $8 $12 $43 $112 $18 $22 $43 $16 $9 $13 $24 $9 $8 $25 $76 $29 $35 $31 $25 $34 $21 $58 $8 $0 $34 $15 $1 $16 $31 $303 $15 $62 $104 $5 $26 $163 $2 $79 $10 $42 $18 $29 $36 $114 $170 $106 $7 $63 $15 $78 $58 $0 $4 $41 $28 $9 $24 $46 $15 $38 $26 $31 $1 $36 $28 $13 $64 $5 $22 $44 $58 $14 $82 $28 $25 $32 $105 $53 $32 $33 $103 $15 $23 $11 $33 $12 $18 $73 $41 $8 $19 $17 $27 $23 $11 $2 $20 $3 $0 $115 $20 $65 $16 $87 $19 $8 $2 $5 $59 $51 $38 $31 $38 $11 $52 $85 $24 $56 $11 $44 $22 $17 $19 $43 $12 $17 $37 $1 $119 $33 $33 $10 $75 $16 $2 $57 $9 $63 $11 $19 $35 $30 $72 $14 $16 $9 $28 $73 $11 $45 $13 $0 $18 $3 $19 $14 $5 $15 $35 $7 $1 $129 $29 $27 $19 $19 $13 $11 $44 $6 $6 $8 $5 $17 $28 $98 $31 $7 $785 $1 $9 $9 $81 $11 $61 $44 $62 $10 $37 $11 $41 $38 $25 $19 $28 $64 $24 $36 $48 $4 $5 $15 $13 $10 $22 $85 $2 $33 $6 $15 $13 $38 $18 $0 $242 $63 $30 $14 $35 $46 $8 $41 $20 $48 $1 $417 $51 $7 $49 $37 $133 $8 $0 $34 $5 $15 $17 $25 $68 $60 $1 $10 $11 $8 $3 $109 $10 $24 $9 $123 $24 $155 $2 $57 $15 $28 $13 $88 $239 $32 $12 $23 $9 $54 $30 $10 $163 $13 $148 $14 $35 $20 $13 $19 $33 $13 $37 $4 $58 $72 $43 $15 $13 $68 $34 $46 $14 $7 $37 $35 $22 $8 $42 $20 $95 $0 $18 $7 $54 $38 $20 $545 $24 $31 $8 $50 $18 $22 $19 $8 $63 $6 $9 $64 $3 $13 $40 $13 $16 $10 $11 $65 $62 $27 $23 $3 $7 $52 $55 $15 $8 $10 $15 $3 $16 $43 $21 $30 $32 $114 $15 $63 $54 $52 $59 $15 $54 $1 $11 $51 $35 $26 $42 $9 $3 $76 $16 $11 $23 $4 $52 $1 $15 $4 $40 $61 $2 $35 $129 $22 $18 $11 $47 $53 $12 $7 $44 $36 $104 $1 $22 $8 $4 $12 $19 $16 $7 $8 $28 $38 $7 $11 $48 $19 $95 $20 $20 $52 $25 $22 $9 $9 $7 $49 $355 $30 $136 $81 $23 $23 $60 $15 $20 $1 $5 $10 $8 $7 $558 $20 $37 $6 $33 $11 $47 $36 $18 $32 $16 $62 $9 $52 $205 $94 $1 $19 $142 $79 $1 $33 $18 $12 $55 $31 $36 $5 $111 $21 $24 $23 $43 $6 $12 $54 $550 $78 $177 $37 $44 $34 $2 $24 $176 $4 $18 $3 $25 $19 $10 $4 $40 $9 $30 $3 $4 $9 $31 $17 $15 $15 $35 $106 $32 $40 $23 $17 $82 $75 $17 $26 $13 $60 $53 $9 $56 $86 $18 $30 $108 $175 $9 $46 $28 $24 $28 $21 $5 $5 $96 $70 $34 $53 $4 $15 $39 $41 $86 $14 $76 $13 $10 $8 $6 $28 $3 $26 $33 $7 $55 $141 $31 $32 $6 $29 $113 $11 $82 $28 $12 $38 $30 $10 $20 $102 $46 $46 $6 $91 $25 $84 $7 $37 $59 $16 $41 $65 $9 $71 $328 $57 $59 $100 $16 $17 $15 $16 $21 $39 $15 $11 $49 $17 $39 $9 $8 $20 $19 $31 $59 $18 $18 $16 $42 $146 $61 $18 $26 $6 $16 $23 $60 $29 $29 $11 $2 $17 $31 $4 $18 $45 $25 $6 $32 $9 $18 $40 $18 $59 $73 $7 $65 $41 $5 $68 $16 $6 $38 $111 $2 $2 $19 $8 $15 $26 $15 $6 $1 $8 $14 $19 $10 $11 $5 $59 $52 $27 $25 $49 $38 $15 $3 $29 $2 $13 $1 $7 $26 $55 $30 $33 $60 $61 $1 $23 $570 $88 $79 $61 $26 $101 $6 $35 $15 $42 $45 $20 $15 $20 $135 $68 $133 $8 $25 $52 $47 $53 $44 $16 $42 $47 $37 $16 $49 $11 $16 $135 $41 $29 $8 $40 $1 $54 $74 $94 $16 $52 $27 $26 $24 $7 $7 $29 $54 $21 $5 $34 $66 $39 $32 $13 $8 $55 $18 $32 $22 $53 $46 $56 $50 $38 $132 $55 $69 $10 $60 $20 $10 $11 $50 $100 $15 $8 $362 $152 $19 $22 $43 $38 $21 $19 $20 $52 $22 $8 $0 $10 $48 $57 $29 $98 $26 $10 $5 $63 $52 $28 $22 $51 $18 $12 $4 $27 $6 $47 $18 $4 $54 $52 $20 $2 $62 $40 $9 $36 $109 $12 $9 $0 $195 $55 $7 $108 $11 $1 $55 $20 $7 $18 $4 $21 $45 $21 $13 $14 $42 $25 $4 $57 $27 $17 $53 $13 $31 $34 $15 $13 $41 $12 $56 $20 $6 $31 $13 $177 $52 $48 $10 $2 $8 $79 $14 $15 $54 $18 $22 $24 $144 $13 $92 $17 $2 $208 $65 $54 $7 $8 $18 $37 $22 $2 $13 $44 $19 $115 $28 $7 $88 $41 $370 $0 $17 $57 $58 $54 $40 $32 $23 $2 $6 $8 $32 $84 $9 $95 $14 $6 $60 $1 $32 $35 $23 $18 $2 $34 $14 $6 $36 $18 $43 $128 $79 $33 $51 $62 $12 $78 $9 $86 $0 $21 $6 $51 $15 $16 $35 $40 $13 $15 $2 $54 $8 $1 $9 $270 $117 $29 $9 $45 $2 $39 $12 $14 $70 $102 $29 $81 $29 $11 $23 $81 $3 $67 $23 $5 $11 $267 $16 $2 $10 $28 $31 $86 $12 $8 $6 $16 $12 $8 $39 $23 $82 $17 $34 $4 $132 $7 $149 $52 $55 $5 $1 $7 $0 $90 $29 $8 $7 $61 $14 $44 $145 $19 $60 $45 $83 $58 $20 $4 $51 $4 $26 $31 $13 $20 $31 $293 $60 $22 $25 $67 $18 $11 $4 $16 $35 $70 $6 $16 $108 $27 $4 $17 $85 $117 $91 $16 $5 $17 $15 $3 $12 $35 $18 $20 $373 $9 $94 $12 $70 $21 $87 $14 $95 $16 $33 $37 $50 $2 $72 $137 $24 $8 $26 $8 $12 $49 $1 $22 $0 $13 $35 $11 $29 $42 $25 $5 $18 $21 $43 $16 $15 $6 $55 $63 $9 $28 $13 $0 $30 $24 $28 $7 $29 $29 $46 $47 $56 $59 $58 $27 $0 $16 $62 $25 $1 $0 $12 $55 $102 $16 $24 $4 $17 $30 $30 $31 $26 $32 $3 $57 $25 $12 $13 $22 $33 $5 $13 $11 $15 $17 $22 $24 $30 $16 $17 $0 $43 $11 $15 $26 $4 $36 $58 $120 $12 $205 $28 $6 $4 $52 $138 $53 $27 $20 $20 $89 $9 $18 $3 $11 $28 $11 $14 $21 $2 $59 $62 $33 $9 $2 $4 $65 $12 $39 $42 $13 $53 $51 $18 $492 $32 $44 $20 $13 $62 $97 $15 $20 $63 $11 $17 $24 $226 $42 $22 $8 $85 $28 $26 $18 $68 $20 $18 $17 $26 $16 $18 $11 $2 $32 $53 $1 $20 $13 $46 $6 $38 $17 $2 $16 $13 $64 $9 $184 $12 $49 $35 $11 $20 $85 $13 $5 $4 $20 $21 $59 $18 $1 $105 $13 $8 $4 $9 $9 $39 $146 $28 $38 $41 $2 $7 $11 $20 $84 $1 $45 $15 $56 $29 $23 $26 $33 $53 $29 $80 $39 $8 $22 $5 $49 $201 $2 $14 $31 $16 $18 $80 $52 $3 $56 $30 $22 $2 $507 $12 $28 $130 $8 $8 $22 $2 $46 $11 $10 $17 $31 $36 $36 $14 $8 $12 $37 $33 $20 $55 $0 $24 $33 $21 $3 $45 $17 $21 $3 $13 $4 $65 $39 $13 $37 $17 $4 $8 $28 $7 $18 $48 $19 $16 $71 $4 $2 $160 $12 $116 $13 $50 $20 $5 $35 $1 $12 $56 $31 $134 $10 $36 $27 $4 $33 $38 $1 $50 $28 $17 $26 $3 $17 $39 $14 $460 $54 $5 $35 $38 $18 $8 $19 $0 $18 $1 $2 $12 $3 $43 $22 $1 $57 $3 $2 $19 $17 $46 $35 $19 $17 $11 $21 $13 $45 $10 $10 $28 $22 $8 $11 $16 $2 $47 $25 $29 $24 $107 $23 $12 $7 $9 $33 $44 $36 $67 $25 $6 $23 $12 $31 $65 $11 $36 $11 $12 $14 $51 $6 $9 $26 $162

In [24]:
# Modeling
# Random forest with NLP features
np.random.seed(40)
y_train = prices_train
y_test = prices_test

# Train 
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=4)
model.fit(X_train, y_train)

# Predict 
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluate 
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MSE: {train_mse: 0.2f}")
print(f"Train R2 Score: {train_r2: 0.2f}%")
print(f"Test MSE: {test_mse: 0.2f}")
print(f"Test R2 Score: {test_r2: 0.2f}%")

Train MSE:  806.38
Train R2 Score:  0.93%
Test MSE:  4098.00
Test R2 Score:  0.34%

In [25]:
# Test dataset
def random_forest(item):
    X_test = vectorizer.transform([item.summary])
    # In case we got - result then it gonna be zero
    return max(model.predict(X_test)[0], 0)

In [26]:
# Test single datapoint
random_forest(items[0])

9.209200000000008

In [27]:
# Evaluation
evaluate(random_forest, test)

  0%|          | 0/2000 [00:00<?, ?it/s]

$7 $55 $10 $5 $6 $6 $0 $11 $2 $9 $6 $29 $13 $6 $26 $2 $8 $6 $297 $76 $8 $6 $57 $8 $8 $11 $3 $8 $0 $9 $4 $24 $27 $740 $2 $16 $19 $6 $24 $3 $12 $110 $10 $3 $22 $8 $9 $21 $1 $1 $13 $15 $21 $0 $6 $5 $27 $7 $10 $8 $21 $8 $17 $15 $148 $154 $16 $3 $13 $2 $9 $2 $7 $35 $13 $18 $56 $8 $36 $212 $15 $2 $6 $111 $14 $89 $4 $19 $11 $17 $10 $1 $12 $9 $14 $11 $0 $37 $21 $2 $17 $94 $21 $13 $1 $27 $26 $3 $11 $3 $128 $18 $44 $90 $15 $52 $16 $100 $16 $10 $20 $11 $10 $4 $88 $29 $20 $7 $7 $141 $8 $18 $203 $43 $4 $3 $1 $17 $58 $1 $5 $16 $14 $4 $6 $6 $7 $13 $10 $15 $9 $29 $3 $1 $16 $12 $26 $1 $70 $3 $3 $30 $4 $2 $62 $250 $9 $13 $32 $7 $6 $9 $43 $119 $8 $141 $44 $25 $2 $2 $13 $3 $10 $5 $144 $10 $29 $18 $4 $7 $9 $1 $34 $7 $12 $7 $27 $0 $13 $19 $25 $4 $18 $9 $10 $6 $62 $35 $12 $3 $10 $24 $78 $5 $2 $156 $18 $1 $21 $1 $35 $1 $4 $48 $2 $45 $19 $9 $13 $5 $17 $5 $18 $8 $28 $20 $9 $33 $8 $7 $12 $4 $0 $9 $10 $10 $8 $17 $59 $292 $39 $39 $14 $1 $43 $463 $86 $14 $0 $19 $1 $11 $16 $7 $12 $12 $7 $27 $30 $37 $24 $52 $13 $1 $10 $7 $23 $10 $29 $21 $18 $14 $3 $6 $53 $12 $72 $31 $7 $58 $83 $12 $19 $7 $6 $23 $3 $118 $17 $254 $4 $57 $74 $151 $15 $3 $14 $9 $48 $18 $19 $136 $15 $21 $23 $6 $5 $62 $14 $3 $6 $8 $8 $3 $9 $7 $12 $20 $27 $1 $23 $47 $151 $2 $12 $106 $9 $12 $4 $25 $19 $11 $121 $67 $8 $16 $9 $11 $1 $16 $9 $4 $9 $578 $5 $7 $6 $7 $67 $16 $43 $10 $3 $75 $15 $13 $32 $5 $28 $2 $4 $18 $7 $13 $61 $9 $6 $12 $6 $13 $36 $6 $5 $5 $18 $13 $27 $4 $13 $83 $30 $9 $8 $14 $11 $14 $6 $75 $8 $13 $29 $27 $117 $109 $11 $69 $1 $20 $2 $11 $3 $18 $37 $19 $44 $18 $16 $11 $61 $31 $40 $14 $13 $21 $16 $24 $3 $44 $15 $3 $6 $43 $13 $42 $9 $4 $8 $27 $4 $63 $5 $69 $14 $11 $28 $3 $5 $67 $20 $9 $7 $10 $2 $13 $24 $24 $80 $8 $14 $11 $0 $6 $3 $23 $46 $13 $5 $4 $10 $7 $8 $20 $12 $25 $16 $0 $12 $4 $12 $6 $9 $27 $152 $31 $14 $14 $679 $21 $15 $47 $7 $27 $19 $3 $6 $18 $5 $12 $64 $23 $127 $5 $6 $137 $175 $6 $6 $130 $2 $1 $4 $3 $13 $41 $2 $81 $12 $9 $18 $43 $20 $3 $5 $20 $15 $171 $8 $34 $3 $13 $22 $14 $98 $73 $11 $4 $50 $53 $13 $4 $20 $29 $47 $12 $7 $98 $34 $1 $5 $1 $127 $29 $6 $14 $2 $1 $1 $153 $8 $7 $2 $8 $0 $5 $26 $52 $7 $20 $4 $123 $53 $35 $9 $21 $18 $12 $34 $347 $88 $64 $14 $65 $82 $2 $26 $14 $5 $37 $24 $2 $10 $53 $13 $7 $12 $19 $44 $24 $5 $15 $8 $15 $1 $54 $9 $50 $7 $8 $10 $25 $10 $19 $6 $22 $11 $20 $14 $5 $8 $8 $7 $4 $23 $4 $15 $8 $5 $190 $6 $128 $17 $12 $1 $11 $44 $3 $26 $9 $4 $5 $2 $8 $292 $4 $7 $36 $5 $9 $190 $26 $34 $12 $4 $7 $14 $10 $18 $191 $54 $0 $25 $1 $7 $94 $31 $16 $6 $14 $2 $18 $31 $7 $9 $15 $14 $11 $4 $15 $63 $19 $8 $5 $49 $11 $1 $57 $61 $7 $36 $47 $6 $12 $5 $58 $10 $4 $14 $45 $27 $11 $98 $13 $20 $13 $15 $10 $0 $18 $3 $17 $6 $24 $182 $9 $12 $15 $6 $0 $6 $28 $2 $39 $28 $17 $15 $13 $15 $13 $18 $15 $8 $29 $19 $11 $0 $12 $3 $29 $18 $2 $25 $123 $15 $26 $15 $15 $33 $11 $10 $4 $59 $6 $3 $17 $26 $4 $13 $39 $23 $68 $4 $19 $50 $14 $11 $8 $2 $15 $27 $4 $23 $9 $1 $4 $127 $3 $10 $10 $9 $11 $14 $45 $4 $7 $26 $35 $13 $27 $70 $6 $11 $728 $12 $15 $15 $98 $3 $10 $29 $9 $8 $10 $27 $7 $35 $5 $15 $1 $51 $7 $39 $6 $12 $24 $5 $16 $15 $7 $7 $1 $1 $4 $21 $75 $19 $5 $9 $246 $20 $5 $19 $15 $23 $15 $29 $4 $50 $29 $414 $68 $11 $5 $33 $105 $18 $14 $11 $4 $3 $11 $1 $27 $23 $5 $9 $2 $9 $17 $83 $26 $9 $19 $151 $7 $175 $22 $3 $9 $74 $19 $7 $136 $18 $18 $26 $2 $24 $2 $13 $73 $3 $201 $23 $10 $4 $2 $63 $4 $17 $2 $2 $16 $9 $7 $1 $3 $41 $6 $7 $4 $14 $3 $3 $2 $16 $1 $24 $25 $51 $3 $2 $111 $12 $13 $358 $0 $3 $11 $37 $2 $9 $0 $65 $139 $3 $27 $10 $4 $16 $10 $38 $8 $10 $40 $57 $10 $3 $13 $3 $21 $2 $152 $22 $28 $7 $24 $2 $10 $1 $7 $36 $7 $135 $4 $70 $53 $80 $47 $19 $48 $7 $2 $2 $28 $3 $9 $1 $3 $4 $3 $29 $9 $9 $31 $13 $12 $27 $56 $27 $28 $2 $25 $142 $16 $3 $40 $81 $13 $5 $5 $19 $67 $0 $10 $81 $10 $21 $2 $13 $22 $29 $70 $34 $4 $9 $17 $2 $34 $12 $15 $2 $8 $66 $3 $6 $1 $19 $422 $7 $65 $33 $14 $7 $11 $4 $9 $11 $13 $7 $5 $1 $480 $5 $17 $27 $6 $4 $23 $12 $16 $36 $31 $33 $15 $54 $196 $62 $13 $9 $173 $4 $3 $16 $24 $10 $5 $14 $1 $18 $105 $11 $169 $6 $8 $7 $0 $10 $477 $8 $108 $10 $11 $9 $2 $7 $209 $2 $7 $2 $12 $24 $1 $12 $47 $11 $15 $10 $1 $5 $6 $4 $4 $52 $24 $39 $40 $58 $15 $7 $34 $30 $1 $33 $3 $19 $6 $7 $16 $18 $46 $19 $117 $61 $1 $2 $13 $2 $18 $9 $16 $51 $6 $7 $12 $10 $14 $6 $16 $1 $26 $19 $76 $13 $7 $53 $28 $10 $1 $17 $1 $5 $0 $75 $6 $6 $5 $9 $114 $26 $137 $4 $2 $66 $5 $2 $7 $9 $23 $7 $11 $28 $5 $22 $64 $9 $8 $3 $12 $10 $68 $48 $234 $38 $5 $32 $4 $4 $8 $125 $10 $4 $7 $2 $45 $5 $2 $8 $11 $16 $9 $24 $54 $19 $2 $10 $25 $50 $5 $8 $71 $20 $4 $22 $40 $44 $11 $5 $6 $0 $3 $1 $38 $15 $8 $1 $15 $9 $9 $15 $27 $91 $13 $2 $68 $5 $3 $67 $3 $6 $12 $171 $4 $12 $19 $3 $1 $15 $12 $8 $40 $12 $12 $0 $2 $20 $1 $81 $79 $29 $1 $42 $50 $11 $3 $11 $8 $3 $16 $2 $25 $1 $9 $14 $13 $8 $9 $3 $547 $33 $79 $27 $8 $114 $2 $84 $8 $15 $8 $6 $8 $2 $188 $6 $86 $16 $13 $67 $1 $19 $32 $12 $34 $15 $16 $4 $12 $9 $38 $131 $29 $23 $19 $24 $9 $29 $14 $151 $3 $1 $10 $3 $21 $2 $12 $7 $1 $2 $19 $21 $5 $7 $31 $13 $4 $6 $26 $0 $16 $2 $13 $59 $6 $12 $133 $16 $6 $1 $7 $39 $14 $16 $7 $46 $26 $9 $395 $145 $2 $0 $11 $5 $68 $20 $3 $67 $3 $0 $6 $9 $8 $43 $0 $54 $76 $6 $2 $1 $19 $1 $22 $9 $11 $16 $19 $18 $55 $79 $0 $5 $43 $90 $2 $13 $19 $6 $2 $15 $71 $3 $12 $4 $22 $113 $52 $21 $15 $10 $21 $25 $5 $17 $12 $18 $55 $2 $12 $10 $5 $16 $15 $10 $12 $25 $1 $10 $4 $9 $18 $4 $4 $26 $20 $2 $6 $2 $19 $143 $94 $3 $2 $6 $25 $31 $7 $4 $2 $2 $1 $6 $57 $5 $36 $2 $4 $244 $9 $65 $1 $9 $68 $7 $9 $12 $0 $35 $24 $123 $4 $20 $22 $1 $283 $12 $15 $68 $8 $22 $4 $8 $7 $9 $5 $15 $46 $50 $4 $29 $4 $12 $13 $5 $10 $76 $28 $24 $7 $10 $17 $28 $10 $7 $3 $83 $58 $0 $57 $8 $4 $16 $18 $15 $4 $20 $34 $96 $20 $2 $11 $9 $10 $14 $4 $16 $28 $5 $6 $211 $78 $4 $11 $29 $15 $55 $2 $14 $47 $124 $15 $52 $29 $9 $24 $16 $1 $5 $40 $53 $8 $243 $101 $4 $5 $2 $3 $2 $1 $14 $13 $11 $2 $16 $1 $6 $17 $11 $18 $15 $147 $50 $103 $25 $47 $6 $34 $18 $21 $5 $29 $7 $31 $122 $1 $46 $125 $20 $60 $2 $12 $110 $18 $0 $4 $6 $19 $10 $1 $33 $18 $349 $17 $25 $67 $30 $11 $2 $85 $9 $2 $10 $3 $17 $126 $1 $30 $12 $108 $52 $117 $16 $17 $3 $3 $0 $20 $10 $11 $12 $475 $4 $200 $1 $97 $0 $115 $30 $61 $2 $3 $26 $39 $14 $8 $126 $9 $9 $14 $15 $4 $17 $1 $6 $16 $5 $3 $58 $15 $46 $11 $11 $2 $7 $10 $2 $7 $30 $129 $9 $2 $9 $9 $12 $17 $19 $19 $6 $8 $0 $25 $10 $11 $47 $2 $16 $16 $6 $80 $9 $12 $11 $6 $34 $103 $18 $14 $1 $44 $4 $6 $4 $11 $10 $24 $1 $2 $3 $15 $4 $1 $10 $27 $12 $11 $1 $24 $0 $4 $29 $9 $10 $19 $25 $8 $2 $1 $63 $37 $146 $9 $237 $6 $2 $0 $73 $124 $3 $2 $20 $75 $119 $10 $24 $5 $6 $10 $3 $3 $69 $14 $15 $91 $8 $18 $1 $5 $0 $1 $3 $69 $18 $15 $72 $7 $558 $10 $6 $3 $9 $27 $6 $11 $11 $13 $13 $25 $22 $150 $6 $3 $36 $41 $18 $22 $10 $53 $2 $3 $1 $22 $4 $3 $10 $2 $26 $77 $12 $9 $3 $64 $10 $10 $65 $32 $9 $1 $9 $5 $134 $0 $9 $6 $11 $6 $27 $5 $11 $2 $43 $25 $77 $4 $10 $166 $0 $13 $11 $2 $23 $16 $94 $17 $40 $11 $41 $5 $14 $20 $149 $12 $5 $6 $52 $12 $5 $6 $42 $3 $2 $227 $22 $4 $14 $14 $24 $211 $9 $30 $7 $17 $93 $60 $48 $17 $2 $6 $4 $19 $431 $11 $8 $78 $15 $22 $6 $13 $28 $9 $25 $30 $33 $3 $32 $24 $18 $35 $21 $18 $27 $46 $8 $33 $46 $32 $5 $32 $31 $3 $11 $8 $23 $14 $23 $20 $29 $2 $13 $20 $30 $22 $25 $45 $13 $9 $63 $29 $3 $152 $12 $113 $25 $51 $28 $6 $39 $12 $5 $7 $24 $129 $20 $33 $40 $2 $30 $30 $5 $58 $37 $0 $10 $5 $30 $46 $5 $436 $59 $6 $21 $34 $31 $9 $24 $27 $10 $21 $3 $7 $30 $21 $25 $2 $41 $4 $30 $47 $29 $30 $78 $9 $29 $33 $30 $27 $7 $3 $2 $35 $27 $29 $26 $29 $4 $38 $25 $10 $42 $101 $40 $7 $8 $7 $30 $29 $47 $39 $20 $1 $23 $3 $28 $54 $47 $9 $28 $9 $14 $53 $11 $13 $10 $134

In [28]:
# Modeling
# XGBoost with NLP features
np.random.seed(40)
feature_columns = selected_words
y_train = prices_train
y_test = prices_test

# Train 
model = xgb.XGBRegressor(n_estimators=1000, random_state=42, n_jobs=4, learning_rate=0.1)
model.fit(X_train, y_train)

# Predict 
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Evaluate 
train_mse = mean_squared_error(y_train, y_train_pred)
train_r2 = r2_score(y_train, y_train_pred)
test_mse = mean_squared_error(y_test, y_test_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train MSE: {train_mse: 0.2f}")
print(f"Train R2 Score: {train_r2: 0.2f}%")
print(f"Test MSE: {test_mse: 0.2f}")
print(f"Test R2 Score: {test_r2: 0.2f}%")

Train MSE:  742.03
Train R2 Score:  0.93%
Test MSE:  4209.67
Test R2 Score:  0.32%

In [29]:
# Test dataset
def xgb(item):
    X_test = vectorizer.transform([item.summary])
    # In case we got - result then it gonna be zero
    return max(model.predict(X_test)[0], 0)

In [30]:
# Test single datapoint
xgb(items[0])

9.031963

In [31]:
# Evaluation
evaluate(xgb, test)

  0%|          | 0/2000 [00:00<?, ?it/s]

$35 $103 $15 $5 $4 $23 $2 $17 $1 $4 $15 $14 $30 $11 $13 $1 $0 $3 $307 $113 $49 $26 $19 $19 $3 $9 $7 $21 $6 $0 $3 $13 $8 $708 $7 $49 $29 $13 $4 $13 $110 $134 $11 $6 $67 $23 $26 $4 $1 $1 $30 $15 $27 $1 $0 $20 $11 $6 $17 $14 $29 $21 $22 $49 $64 $114 $12 $8 $5 $13 $11 $0 $11 $8 $11 $24 $85 $21 $36 $211 $14 $0 $14 $135 $31 $79 $3 $32 $2 $9 $14 $3 $2 $8 $14 $3 $6 $22 $24 $3 $29 $57 $11 $15 $35 $35 $13 $37 $15 $1 $216 $10 $60 $57 $12 $18 $16 $83 $4 $0 $42 $8 $77 $2 $87 $24 $81 $9 $10 $184 $12 $3 $134 $22 $16 $13 $1 $132 $69 $3 $13 $24 $2 $15 $8 $2 $5 $29 $14 $57 $8 $17 $22 $11 $44 $20 $16 $18 $65 $14 $10 $43 $3 $16 $67 $247 $42 $41 $30 $11 $6 $27 $4 $158 $13 $87 $8 $0 $28 $1 $11 $10 $13 $17 $135 $40 $45 $36 $5 $4 $62 $10 $56 $4 $22 $36 $7 $4 $10 $39 $8 $6 $11 $58 $9 $22 $30 $13 $18 $1 $14 $48 $110 $7 $12 $127 $22 $9 $25 $7 $29 $28 $22 $37 $1 $43 $24 $30 $7 $8 $34 $18 $10 $12 $3 $17 $123 $35 $5 $6 $15 $5 $1 $3 $26 $21 $13 $7 $61 $261 $64 $31 $27 $6 $3 $507 $73 $9 $14 $21 $5 $1 $28 $9 $11 $14 $11 $9 $37 $61 $31 $7 $15 $4 $53 $8 $28 $22 $32 $17 $6 $10 $12 $15 $53 $14 $67 $23 $21 $67 $72 $28 $59 $33 $12 $33 $3 $103 $18 $126 $4 $96 $68 $34 $2 $6 $10 $1 $37 $23 $3 $147 $12 $22 $59 $0 $3 $85 $25 $13 $2 $10 $10 $7 $1 $13 $0 $3 $10 $9 $44 $36 $100 $1 $3 $62 $11 $11 $12 $22 $10 $33 $22 $9 $12 $1 $31 $14 $3 $14 $7 $25 $18 $625 $16 $14 $10 $22 $42 $28 $33 $11 $13 $46 $12 $6 $38 $1 $13 $0 $7 $24 $2 $36 $73 $23 $11 $41 $4 $113 $13 $7 $2 $6 $17 $19 $4 $6 $2 $100 $40 $29 $12 $13 $22 $11 $13 $65 $22 $14 $50 $13 $48 $57 $17 $60 $12 $14 $3 $13 $3 $14 $15 $33 $50 $21 $9 $8 $55 $60 $49 $27 $15 $28 $75 $6 $9 $9 $3 $10 $12 $39 $4 $12 $20 $1 $10 $13 $9 $115 $13 $62 $3 $1 $34 $18 $12 $47 $5 $6 $22 $4 $31 $10 $42 $5 $29 $5 $12 $27 $27 $16 $5 $7 $34 $4 $5 $3 $9 $7 $20 $0 $22 $19 $5 $16 $4 $4 $17 $17 $11 $50 $151 $31 $8 $20 $638 $30 $7 $56 $4 $21 $15 $6 $11 $19 $2 $18 $63 $35 $125 $22 $6 $77 $410 $18 $6 $62 $4 $24 $10 $0 $24 $38 $62 $88 $15 $13 $7 $53 $17 $8 $65 $35 $17 $146 $12 $24 $17 $2 $9 $20 $59 $77 $20 $6 $36 $54 $5 $2 $10 $18 $26 $58 $26 $120 $26 $9 $18 $9 $106 $11 $10 $15 $10 $4 $11 $172 $13 $4 $7 $3 $17 $8 $27 $44 $6 $21 $38 $143 $103 $16 $4 $7 $26 $19 $4 $322 $138 $87 $23 $122 $104 $1 $4 $2 $18 $44 $26 $4 $11 $53 $12 $21 $17 $18 $58 $9 $4 $10 $24 $5 $2 $28 $2 $43 $6 $3 $20 $6 $24 $22 $6 $4 $22 $10 $49 $8 $4 $17 $11 $12 $4 $7 $4 $15 $14 $112 $21 $158 $17 $6 $18 $32 $30 $6 $16 $25 $1 $8 $15 $65 $204 $15 $52 $82 $5 $12 $164 $18 $19 $4 $22 $15 $28 $10 $36 $187 $23 $14 $23 $4 $31 $92 $36 $13 $1 $39 $7 $15 $32 $2 $4 $34 $26 $3 $16 $15 $29 $7 $6 $17 $41 $20 $19 $45 $74 $17 $12 $55 $6 $25 $12 $134 $11 $3 $11 $34 $27 $18 $21 $44 $3 $26 $63 $22 $43 $28 $3 $15 $2 $21 $160 $0 $19 $12 $41 $4 $6 $15 $7 $41 $8 $18 $21 $14 $14 $20 $26 $7 $57 $10 $26 $7 $10 $7 $25 $20 $5 $15 $30 $34 $4 $121 $3 $21 $11 $7 $59 $22 $53 $3 $9 $26 $23 $37 $27 $50 $28 $50 $21 $0 $52 $12 $1 $10 $8 $7 $24 $17 $22 $22 $0 $14 $124 $3 $12 $3 $8 $16 $41 $33 $2 $0 $38 $11 $8 $31 $45 $6 $5 $745 $19 $14 $28 $69 $6 $37 $177 $48 $11 $18 $20 $3 $2 $13 $1 $2 $47 $7 $49 $11 $78 $11 $5 $15 $19 $19 $6 $1 $18 $2 $13 $9 $2 $3 $6 $186 $33 $17 $22 $10 $68 $20 $30 $2 $38 $5 $403 $37 $3 $7 $12 $104 $8 $2 $0 $4 $1 $21 $15 $29 $28 $7 $24 $11 $7 $6 $76 $5 $24 $7 $132 $1 $165 $1 $19 $11 $54 $26 $7 $196 $29 $35 $7 $0 $14 $20 $16 $125 $6 $171 $22 $24 $3 $12 $61 $33 $17 $19 $1 $20 $4 $23 $4 $6 $20 $12 $16 $2 $1 $27 $13 $15 $12 $3 $27 $8 $39 $11 $4 $11 $25 $9 $374 $6 $11 $3 $35 $20 $16 $9 $73 $5 $9 $16 $22 $3 $5 $29 $44 $5 $3 $3 $51 $2 $11 $20 $8 $13 $5 $138 $13 $2 $9 $23 $13 $29 $4 $8 $44 $13 $123 $1 $30 $37 $126 $63 $25 $82 $5 $4 $10 $1 $4 $10 $10 $4 $6 $7 $28 $16 $2 $25 $6 $14 $10 $40 $33 $4 $14 $69 $85 $6 $7 $32 $29 $2 $6 $48 $23 $80 $5 $0 $92 $7 $22 $2 $9 $6 $74 $15 $29 $3 $2 $4 $4 $62 $3 $3 $10 $10 $38 $1 $7 $8 $34 $387 $16 $51 $67 $3 $10 $55 $6 $21 $12 $6 $9 $1 $8 $519 $10 $24 $5 $2 $8 $36 $23 $6 $43 $205 $30 $28 $7 $196 $11 $11 $0 $161 $0 $1 $14 $22 $15 $22 $22 $5 $22 $58 $22 $18 $2 $35 $11 $11 $17 $468 $25 $134 $17 $17 $10 $5 $23 $216 $11 $8 $11 $25 $5 $1 $3 $27 $1 $14 $7 $3 $4 $5 $13 $3 $38 $32 $107 $76 $50 $8 $6 $79 $32 $10 $15 $9 $35 $1 $20 $27 $9 $36 $5 $120 $69 $5 $7 $23 $17 $29 $10 $3 $16 $10 $9 $45 $7 $41 $5 $23 $6 $54 $8 $104 $12 $5 $34 $5 $1 $3 $28 $7 $11 $7 $52 $17 $24 $12 $29 $204 $32 $125 $11 $2 $63 $1 $9 $5 $16 $38 $28 $9 $59 $7 $46 $135 $17 $43 $26 $2 $22 $37 $55 $339 $41 $3 $17 $12 $15 $14 $41 $31 $1 $10 $6 $35 $7 $18 $5 $0 $10 $11 $19 $60 $19 $9 $7 $29 $58 $11 $11 $74 $9 $16 $9 $48 $1 $6 $3 $13 $11 $4 $9 $46 $17 $4 $17 $25 $7 $3 $17 $6 $158 $5 $0 $64 $21 $19 $58 $4 $3 $20 $86 $6 $9 $0 $5 $25 $4 $37 $8 $4 $4 $6 $20 $10 $11 $17 $27 $103 $7 $21 $37 $60 $7 $3 $1 $7 $8 $34 $10 $3 $31 $29 $9 $6 $69 $2 $4 $485 $39 $179 $13 $9 $42 $1 $47 $0 $25 $49 $7 $0 $8 $161 $3 $57 $14 $11 $94 $4 $23 $20 $19 $43 $22 $9 $18 $22 $0 $31 $35 $86 $2 $11 $15 $6 $1 $15 $169 $16 $14 $15 $12 $15 $6 $13 $16 $19 $6 $16 $1 $28 $53 $4 $1 $5 $24 $14 $12 $19 $23 $32 $60 $8 $16 $145 $31 $29 $10 $29 $39 $33 $15 $2 $91 $19 $8 $373 $180 $7 $4 $23 $13 $58 $1 $0 $77 $18 $11 $8 $18 $10 $10 $0 $71 $56 $7 $11 $19 $29 $16 $30 $5 $1 $17 $3 $12 $52 $70 $21 $10 $51 $94 $9 $15 $32 $21 $2 $18 $28 $1 $6 $19 $115 $91 $48 $25 $16 $4 $15 $20 $0 $39 $12 $1 $41 $13 $11 $2 $14 $17 $20 $33 $24 $35 $13 $27 $2 $14 $25 $3 $15 $7 $25 $9 $13 $7 $33 $156 $68 $109 $6 $8 $10 $26 $13 $8 $1 $5 $17 $7 $20 $2 $31 $3 $5 $222 $7 $85 $8 $6 $4 $10 $28 $11 $4 $38 $6 $143 $4 $40 $4 $5 $249 $19 $17 $30 $28 $38 $2 $12 $10 $12 $6 $18 $40 $23 $2 $62 $10 $24 $23 $3 $13 $42 $24 $3 $5 $8 $15 $14 $32 $11 $6 $65 $140 $4 $54 $24 $3 $38 $3 $49 $6 $18 $26 $197 $26 $4 $23 $9 $2 $26 $2 $8 $29 $2 $6 $165 $61 $20 $12 $99 $9 $13 $0 $8 $49 $162 $6 $14 $24 $10 $12 $16 $2 $11 $50 $20 $4 $211 $56 $5 $4 $17 $2 $1 $2 $22 $3 $14 $5 $8 $21 $11 $40 $54 $25 $11 $207 $21 $117 $31 $65 $11 $29 $13 $47 $13 $45 $12 $21 $59 $7 $48 $120 $15 $35 $6 $31 $66 $3 $12 $1 $2 $18 $11 $1 $31 $0 $164 $71 $1 $97 $53 $3 $6 $19 $11 $4 $2 $10 $6 $166 $9 $62 $27 $135 $93 $122 $20 $7 $0 $7 $19 $10 $37 $9 $17 $524 $9 $183 $3 $7 $2 $122 $23 $57 $44 $3 $39 $55 $4 $44 $65 $13 $3 $37 $14 $8 $41 $12 $12 $6 $10 $5 $27 $4 $38 $5 $9 $2 $5 $8 $14 $29 $13 $36 $20 $3 $20 $11 $3 $1 $17 $22 $10 $24 $8 $42 $12 $27 $37 $9 $26 $24 $20 $80 $3 $20 $5 $6 $61 $108 $2 $0 $8 $24 $11 $19 $12 $16 $26 $3 $44 $7 $3 $2 $12 $25 $12 $1 $30 $9 $3 $15 $16 $12 $35 $1 $0 $42 $20 $2 $8 $4 $11 $33 $137 $10 $208 $4 $6 $8 $54 $155 $28 $22 $11 $19 $108 $6 $12 $3 $5 $14 $8 $4 $26 $28 $15 $29 $28 $17 $31 $17 $79 $9 $4 $46 $13 $7 $59 $4 $585 $11 $24 $2 $13 $43 $29 $5 $4 $41 $9 $14 $14 $148 $32 $8 $13 $64 $32 $12 $13 $102 $1 $11 $4 $14 $17 $26 $3 $6 $21 $99 $10 $2 $4 $58 $27 $12 $50 $27 $19 $1 $43 $8 $166 $11 $20 $10 $48 $11 $66 $2 $21 $8 $31 $5 $88 $18 $11 $139 $1 $6 $5 $14 $2 $21 $100 $13 $19 $25 $24 $8 $4 $1 $198 $3 $3 $21 $37 $9 $9 $18 $41 $1 $12 $119 $10 $49 $6 $1 $23 $288 $7 $22 $21 $11 $34 $62 $52 $38 $15 $17 $14 $3 $486 $15 $4 $87 $4 $12 $3 $4 $10 $19 $2 $18 $17 $10 $29 $19 $1 $22 $20 $11 $24 $48 $12 $20 $83 $19 $0 $33 $21 $5 $17 $6 $18 $14 $19 $23 $27 $9 $27 $19 $18 $16 $21 $51 $24 $13 $77 $17 $6 $161 $26 $98 $20 $55 $26 $6 $38 $15 $2 $47 $23 $145 $13 $1 $55 $4 $24 $29 $2 $65 $27 $9 $12 $1 $19 $48 $4 $457 $56 $8 $28 $29 $23 $22 $5 $1 $3 $24 $1 $17 $21 $36 $10 $5 $37 $2 $2 $27 $25 $31 $56 $16 $23 $8 $20 $17 $11 $0 $6 $18 $7 $14 $18 $26 $0 $37 $17 $19 $25 $107 $32 $14 $9 $2 $29 $24 $26 $34 $21 $5 $4 $6 $21 $75 $8 $1 $7 $9 $17 $58 $14 $19 $5 $160